const LOADING = 'LOADING'
const ERROR = 'ERROR'
const GET_POPULAR_BOOKS = 'GET_POPULAR_BOOKS'
const GET_CATEGORY_BOOKS = 'GET_CATEGORY_BOOKS'
const GET_BEST_SELLING_BOOKS = 'ET_BEST_SELLING_BOOKS'
const GET_SEARCH_RESULT_BOOKS = 'GET_SEARCH_RESULT_BOOKS'
const GET_TOP_RATED_BOOKS = 'GET_TOP_RATED_BOOKS'
const GET_BOOK_DETAILS = 'GET_BOOK_DETAILS'
const GET_NEW_BOOKS = 'GET_NEW_BOOKS'
const GET_AUTHOR_BOOKS = 'GET_AUTHOR_BOOKS'
const GET_SIMILAR_BOOKS = 'GET_SIMILAR_BOOKS'

export {
    LOADING,
    ERROR,
    GET_BOOK_DETAILS,
    GET_CATEGORY_BOOKS,
    GET_TOP_RATED_BOOKS,
    GET_BEST_SELLING_BOOKS,
    GET_SEARCH_RESULT_BOOKS,
    GET_SIMILAR_BOOKS,
    GET_POPULAR_BOOKS,
    GET_AUTHOR_BOOKS,
    GET_NEW_BOOKS,
}